version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis
  celery:
    image: web-image
    command: celery -A tasks worker -l info
    container_name: celery_worker
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
      - db
  celery-beat:
    image: web-image
    command: celery -A tasks beat -l info
    container_name: celery_beat
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
      - db
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /usr/src/app/entrypoint.sh
    image: web-image
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    # image: postgres:12.0-alpine
    image: postgres
    restart: always
    container_name: bitdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.db.env

volumes:
  postgres_data: